version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - master:
          filters:
            branches:
              only: master

# This key means nothing to CircleCI; it's just a place to keep anchored
# configuration nodes for reuse.
common_settings:
  docker: &docker_setup
    - image: 'circleci/node:10.14.1'
  save_cache: &savecache
    name: Save Yarn Package Cache
    key: 'yarn-packages-{{ checksum "yarn.lock" }}'
    paths:
      - ~/.cache/yarn
  install_packages: &install_packages
    name: Install packages from lockfile
    command: yarn install --frozen-lockfile --ignore-scripts

  full_build: &full_build
    name: Full Build
    command: 'cp packages/venia-concept/.env.dist packages/venia-concept/.env && yarn run clean:dist && yarn run build'

  test_result_path: &test_result_path
    path: "test-results"

jobs:
  master:
    docker: *docker_setup
    steps:
      - checkout
      - run: *install_packages
      - run:
          name: Test Suites
          command: 'yarn run test:ci'
      - run:
          name: Coveralls Coverage Analysis
          command: yarn run coveralls
      - run: *full_build
      - store_test_results: *test_result_path
      - store_artifacts: *test_result_path
  build:
    docker: *docker_setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'yarn-packages-{{ checksum "yarn.lock" }}'
      - run: *install_packages
      - save_cache: *savecache
      - run:
          name: Test Suites and Coverage
          # Test failures should not stop Danger, so hide the exit code.
          command: 'yarn run test:ci && yarn run coveralls || true'
      - run: *full_build
      - run:
          name: DangerCI
          command: yarn run danger

      - store_test_results: *test_result_path
      - store_artifacts: *test_result_path
